### PR TITLE
added: rbac role and service account

### PR DESCRIPTION
**Pull request by paulgrav**
This is a first attempt at fixing #8  

Note sure if values.yaml should enable rbac by default nor whether the role has all the perms necessary. I’ve tested this on my own AKS cluster and it seems to work.

### CODE REVIEW

**Comment by lawrencegripper** [comment]
Thanks Paul, make sense to me. I won't have a chance to pull this down and review properly for a while as I'm back to back for a bit now. 

For ongoing development I think it would it be worth marking this repo as a sample/depreciated and then maintaining a fork under the Sky org for use with Hydra. That way I won't be a bottle neck and you can iterate faster and not rely on the builds from this repo. 

What do you think?

**Comment by paulgrav** [comment]
That does makes sense. I’ve question with regards to the controller itself. It’s main raison d'etre is to allow deployments to reference cluster.local in manifests and then have that swapped out for the correct registry url?
Could we go down the route of bypassing this altogether and inject the correct registry URL somewhere in the CD process?

**Comment by lawrencegripper** [comment]
Yes that's a good option and something I'd strongly consider, think I made a note about this in the README. Ah yes [here it is](https://github.com/lawrencegripper/terraform-provider-kubernetes-yaml/issues/11). 

> This is a task that could be performed by a CD pipeline and careful thought should be used around how this affects clusters if the webhook service isn't available. Currently the solution mutates deployments meaning that pods can be created successfully when the serivce is down allowing the cluster to recover from node failure - however no deployments could be created or updated during this time.

**Comment by lawrencegripper** [comment]
@paulgrav how did you want to proceed on this one?

**Comment by paulgrav** [comment]
@lawrencegripper I couldn’t get the RBAC stuff to work in the end and we’ve parked it. Gonna close this for the time being.

**Pull request closed without merging**
